import { NextRequest, NextResponse } from 'next/server';
import { v4 as uuidv4 } from 'uuid';
import { getAssessment, updateAssessment, addAuditEntry } from '@/lib/db/store';
import { type DimensionSelection } from '@/types/assessment';
import { recommendDimensionSelections } from '@/lib/llm/dimension-screening';

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const assessment = getAssessment(id);
  if (!assessment) {
    return NextResponse.json({ error: 'Assessment not found' }, { status: 404 });
  }
  return NextResponse.json(assessment.dimensionSelections || []);
}

// Generate AI-recommended dimension selections
export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const assessment = getAssessment(id);
    if (!assessment) {
      return NextResponse.json({ error: 'Assessment not found' }, { status: 404 });
    }

    const selections = await recommendDimensionSelections(
      assessment.companyName,
      assessment.industry,
      assessment.companySize || 'medium',
      assessment.companyDescription,
      Boolean(assessment.useMockData)
    );

    updateAssessment(id, { dimensionSelections: selections });

    addAuditEntry({
      id: uuidv4(),
      assessmentId: id,
      action: 'dimension_selections_recommended',
      entityType: 'assessment',
      entityId: id,
      oldValue: null,
      newValue: { selectionCount: selections.filter(s => s.deepAssessment).length },
      reason: assessment.useMockData ? 'Dimension selections generated via Mock Data' : 'Dimension selections generated by LLM',
      actor: 'system',
      timestamp: new Date().toISOString(),
    });

    return NextResponse.json(selections);
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'Dimension screening failed' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const assessment = getAssessment(id);
  if (!assessment) {
    return NextResponse.json({ error: 'Assessment not found' }, { status: 404 });
  }

  const body = await request.json();
  const selections = body.selections as DimensionSelection[];

  if (!Array.isArray(selections)) {
    return NextResponse.json({ error: 'selections array required' }, { status: 400 });
  }

  updateAssessment(id, { dimensionSelections: selections });

  addAuditEntry({
    id: uuidv4(),
    assessmentId: id,
    action: 'dimension_selections_updated',
    entityType: 'assessment',
    entityId: id,
    oldValue: { selections: assessment.dimensionSelections },
    newValue: { selections },
    reason: 'Dimension selections updated',
    actor: 'user',
    timestamp: new Date().toISOString(),
  });

  return NextResponse.json(selections);
}
